GPU tests POC
Signed-off-by: Igor Gitman <igitman@nvidia.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -39,6 +39,29 @@ jobs:
       run: |
         NEMO_SKILLS_CONFIG=cluster_configs/slurm.yaml python tests/check_help.py --all
 
+  gpu-tests:
+    runs-on: self-hosted-nemo-skills
+
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v3
+      with:
+        python-version: "3.10"
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install .
+        pip install -r datasets/requirements.txt
+        pip install pytest pytest-cov pytest-timeout
+    - name: Run all tests
+      run: |
+        nvidia-smi
+        export NEMO_SKILLS_CONFIG=cluster_configs/local.yaml
+        export NEMO_SKILLS_TEST_HF_MODEL=/mnt/datadrive/nemo-skills-data/Meta-Llama-3-8B
+        set -o pipefail # this will make sure next line returns non-0 exit code if tests fail
+        python -m pytest tests/test_conversion.py --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=nemo_skills --cov=pipeline --durations=30 -rs -vvv | tee pytest-coverage.txt
+
   cluster-tests:
     runs-on: ubuntu-latest
 
