Test fixes
Signed-off-by: Igor Gitman <igitman@nvidia.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -3,12 +3,17 @@ name: Unit tests
 on:
   pull_request:
     branches: [ "main" ]
+    types: [ "labeled" ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 permissions:
   contents: read
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  cancel-in-progress: true
 
 jobs:
   unit-tests:
@@ -39,29 +44,6 @@ jobs:
       run: |
         NEMO_SKILLS_CONFIG=cluster_configs/slurm.yaml python tests/check_help.py --all
 
-  gpu-tests:
-    runs-on: self-hosted-nemo-skills
-
-    steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install .
-        pip install -r datasets/requirements.txt
-        pip install pytest pytest-cov pytest-timeout
-    - name: Run all tests
-      run: |
-        nvidia-smi
-        export NEMO_SKILLS_CONFIG=cluster_configs/local.yaml
-        export NEMO_SKILLS_TEST_HF_MODEL=/mnt/datadrive/nemo-skills-data/Meta-Llama-3-8B
-        set -o pipefail # this will make sure next line returns non-0 exit code if tests fail
-        python -m pytest tests/gpu-tests/test_conversion.py --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=nemo_skills --cov=pipeline --durations=30 -rs -vvv | tee pytest-coverage.txt
-
   cluster-tests:
     runs-on: ubuntu-latest
 
@@ -84,3 +66,28 @@ jobs:
     - name: Check datasets preparation
       run: |
         NEMO_SKILLS_CONFIG=cluster_configs/slurm.yaml pytest tests/test_datasets.py
+
+  gpu-tests:
+    runs-on: self-hosted-nemo-skills
+    if: ${{ github.event.label.name == 'Run GPU tests' }}
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v3
+      with:
+        python-version: "3.10"
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install .
+        pip install -r datasets/requirements.txt
+        pip install pytest pytest-cov pytest-timeout
+    - name: Run GPU tests
+      env:
+        HF_TOKEN: ${{ secrets.HF_TOKEN }}
+      run: |
+        nvidia-smi
+        export NEMO_SKILLS_CONFIG=cluster_configs/local.yaml
+        export NEMO_SKILLS_TEST_HF_MODEL=/mnt/datadrive/nemo-skills-data/Meta-Llama-3-8B
+        set -o pipefail # this will make sure next line returns non-0 exit code if tests fail
+        python -m pytest tests/gpu-tests/test_conversion.py --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=nemo_skills --cov=pipeline --durations=30 -rs -vvv | tee pytest-coverage.txt
